version: '3.7'
services:
  backend:
    container_name: vm-update-poc
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app/src
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    networks:
      - default

networks:
  default:
    driver: bridge
